AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - Gemfile
    - Rakefile
    - config.ru
    - node_modules/**/*
  TargetRubyVersion: 2.6.3

Encoding:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Rails/HasAndBelongsToMany:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

